### ISSUE TITLE
Security Checklist

### ISSUE THREAD

**Issue by servomekanism** [Alcaeusd/softsecshop#9]
#### Information Gathering
- [ ]	OTG-INFO-001	Conduct Search Engine Discovery and Reconnaissance for Information Leakage
- [ ]	OTG-INFO-002	Fingerprint Web Server
- [ ]	OTG-INFO-003	Review Webserver Metafiles for Information Leakage
- [ ]	OTG-INFO-004	Enumerate Applications on Webserver
- [ ]	OTG-INFO-005	Review Webpage Comments and Metadata for Information Leakage
- [ ]	OTG-INFO-006	Identify application entry points
- [ ]	OTG-INFO-007	Map execution paths through application
- [ ]	OTG-INFO-008	Fingerprint Web Application Framework
- [ ]	OTG-INFO-009	Fingerprint Web Application
- [ ]	OTG-INFO-010	Map Application Architecture
#### Configuration and Deploy Management Testing
- [ ]	OTG-CONFIG-001	Test Network/Infrastructure Configuration
- [ ]	OTG-CONFIG-002	Test Application Platform Configuration
- [ ]	OTG-CONFIG-003	Test File Extensions Handling for Sensitive Information
- [ ]	OTG-CONFIG-004	Backup and Unreferenced Files for Sensitive Information
- [ ]	OTG-CONFIG-005	Enumerate Infrastructure and Application Admin Interfaces
- [ ]	OTG-CONFIG-006	Test HTTP Methods
- [ ]	OTG-CONFIG-007	Test HTTP Strict Transport Security
- [ ]	OTG-CONFIG-008	Test RIA cross domain policy
#### Identity Management Testing
- [ ]	OTG-IDENT-001	Test Role Definitions
- [ ]	OTG-IDENT-002	Test User Registration Process
- [ ]	OTG-IDENT-003	Test Account Provisioning Process
- [ ]	OTG-IDENT-004	Testing for Account Enumeration and Guessable User Account
- [ ]	OTG-IDENT-005	Testing for Weak or unenforced username policy
- [ ]	OTG-IDENT-006	Test Permissions of Guest/Training Accounts
- [ ]	OTG-IDENT-007	Test Account Suspension/Resumption Process
#### Authentication Testing
- [ ]	OTG-AUTHN-001	Testing for Credentials Transported over an Encrypted Channel
- [ ]	OTG-AUTHN-002	Testing for default credentials
- [ ]	OTG-AUTHN-003	Testing for Weak lock out mechanism
- [ ]	OTG-AUTHN-004	Testing for bypassing authentication schema
- [ ]	OTG-AUTHN-005	Test remember password functionality
- [ ]	OTG-AUTHN-006	Testing for Browser cache weakness
- [ ]	OTG-AUTHN-007	Testing for Weak password policy
- [ ]	OTG-AUTHN-008	Testing for Weak security question/answer
- [ ]	OTG-AUTHN-009	Testing for weak password change or reset functionalities
- [ ]	OTG-AUTHN-010	Testing for Weaker authentication in alternative channel
#### Authorization Testing
- [ ]	OTG-AUTHZ-001	Testing Directory traversal/file include
- [ ]	OTG-AUTHZ-002	Testing for bypassing authorization schema
- [ ]	OTG-AUTHZ-003	Testing for Privilege Escalation
- [ ]	OTG-AUTHZ-004	Testing for Insecure Direct Object References
#### Session Management Testing
- [ ]	OTG-SESS-001	Testing for Bypassing Session Management Schema
- [ ]	OTG-SESS-002	Testing for Cookies attributes
- [ ]	OTG-SESS-003	Testing for Session Fixation
- [ ]	OTG-SESS-004	Testing for Exposed Session Variables
- [ ]	OTG-SESS-005	Testing for Cross Site Request Forgery
- [ ]	OTG-SESS-006	Testing for logout functionality
- [ ]	OTG-SESS-007	Test Session Timeout
- [ ]	OTG-SESS-008	Testing for Session puzzling
#### Data Validation Testing
- [ ]	OTG-INPVAL-001	Testing for Reflected Cross Site Scripting
- [ ]	OTG-INPVAL-002	Testing for Stored Cross Site Scripting
- [ ]	OTG-INPVAL-003	Testing for HTTP Verb Tampering
- [ ]	OTG-INPVAL-004	Testing for HTTP Parameter pollution
- [ ]	OTG-INPVAL-005	Testing for SQL Injection
						Oracle Testing
						MySQL Testing
						SQL Server Testing
						Testing PostgreSQL
						MS Access Testing
						Testing for NoSQL injection
- [ ]	OTG-INPVAL-006	Testing for LDAP Injection
- [ ]	OTG-INPVAL-007	Testing for ORM Injection
- [ ]	OTG-INPVAL-008	Testing for XML Injection
- [ ]	OTG-INPVAL-009	Testing for SSI Injection
- [ ]	OTG-INPVAL-010	Testing for XPath Injection
- [ ]	OTG-INPVAL-011	IMAP/SMTP Injection
- [ ]	OTG-INPVAL-012	Testing for Code Injection
						Testing for Local File Inclusion
						Testing for Remote File Inclusion
- [ ]	OTG-INPVAL-013	Testing for Command Injection
- [ ]	OTG-INPVAL-014	Testing for Buffer overflow
						Testing for Heap overflow
						Testing for Stack overflow
- [ ]					Testing for Format string
- [ ]	OTG-INPVAL-015	Testing for incubated vulnerabilities
- [ ]	OTG-INPVAL-016	Testing for HTTP Splitting/Smuggling
#### Error Handling
- [ ]	OTG-ERR-001		Analysis of Error Codes
- [ ]	OTG-ERR-002		Analysis of Stack Traces
#### Cryptography
- [ ]	OTG-CRYPST-001	Testing for Weak SSL/TSL Ciphers, Insufficient Transport Layer Protection
- [ ]	OTG-CRYPST-002	Testing for Padding Oracle
- [ ]	OTG-CRYPST-003	Testing for Sensitive information sent via unencrypted channels
#### Business Logic Testing
- [ ]	OTG-BUSLOGIC-001	Test Business Logic Data Validation
- [ ]	OTG-BUSLOGIC-002	Test Ability to Forge Requests
- [ ]	OTG-BUSLOGIC-003	Test Integrity Checks
- [ ]	OTG-BUSLOGIC-004	Test for Process Timing
- [ ]	OTG-BUSLOGIC-005	Test Number of Times a Function Can be Used Limits
- [ ]	OTG-BUSLOGIC-006	Testing for the Circumvention of Work Flows
- [ ]	OTG-BUSLOGIC-007	Test Defenses Against Application Mis-use
- [ ]	OTG-BUSLOGIC-008	Test Upload of Unexpected File Types
- [ ]	OTG-BUSLOGIC-009	Test Upload of Malicious Files
#### Client Side Testing
- [ ]	OTG-CLIENT-001	Testing for DOM based Cross Site Scripting
- [ ]	OTG-CLIENT-002	Testing for JavaScript Execution
- [ ]	OTG-CLIENT-003	Testing for HTML Injection
- [ ]	OTG-CLIENT-004	Testing for Client Side URL Redirect
- [ ]	OTG-CLIENT-005	Testing for CSS Injection
- [ ]	OTG-CLIENT-006	Testing for Client Side Resource Manipulation
- [ ]	OTG-CLIENT-007	Test Cross Origin Resource Sharing
- [ ]	OTG-CLIENT-008	Testing for Cross Site Flashing
- [ ]	OTG-CLIENT-009	Testing for Clickjacking
- [ ]	OTG-CLIENT-010	Testing WebSockets
- [ ]	OTG-CLIENT-011	Test Web Messaging
- [ ]	OTG-CLIENT-012	Test Local Storage

**Comment by servomekanism** [comment]
#### Information Gathering
- [x]	OTG-INFO-001	Conduct Search Engine Discovery and Reconnaissance for Information Leakage
- [x]	OTG-INFO-002	Fingerprint Web Server

from `/etc/nginx/nginx.conf` line `16`:
```
	server_tokens off;
```

- [x]	OTG-INFO-003	Review Webserver Metafiles for Information Leakage

No special webserver metafiles exist

- [x]	OTG-INFO-004	Enumerate Applications on Webserver

N/A

- [x]	OTG-INFO-005	Review Webpage Comments and Metadata for Information Leakage

No comments exist at all

- [x]	OTG-INFO-006	Identify application entry points

-1. Network access to port 80/443 TCP

0. All HTTP Headers

1. `validate.php`
	* `username`
	* `password`
	* `token`

2. `index.php`
	* `id`

3. `catalogue.php`
	* `id`

4. `addtocart.php`
	* `searchbar`
	* `token`
	* `prodQuantity`
	* `prodPrice`
	* `prodName`

5. `products.php`
	* `products`
	* `token`

6. `checkout.php`
	* `finalPrice`
	* `finalQuantity`
	* `hiddencheckout`
	* `token`
	* `go`
	* `Submit`

7. `confirmation.php`
	* `customerAddress`
	* `cartDescription`
	* `totalQuantity`
	* `totalPrice`
	* `token`
	* `confirmation`

- [ ]	OTG-INFO-007	Map execution paths through application

Look above.
More can be said here about which php file calls which php file.

- [x]	OTG-INFO-008	Fingerprint Web Application Framework

php

- [x]	OTG-INFO-009	Fingerprint Web Application

done, php, nginx, mysql

- [x]	OTG-INFO-010	Map Application Architecture

2 Tier: PHP + Nginx, Mysql

#### Configuration and Deploy Management Testing
- [x]	OTG-CONFIG-001	Test Network/Infrastructure Configuration

Run nmap, nessus, dirb, whatweb and nikto
nmap should report only ports 22,80,443
nessus should only report that the server uses a self signed ssl certificate that cannot be trusted


- [x]	OTG-CONFIG-002	Test Application Platform Configuration

nothing else to be done here

- [ ]	OTG-CONFIG-003	Test File Extensions Handling for Sensitive Information

should test with burp and nessus and reviewed code (not yet but will do)

- [x]	OTG-CONFIG-004	Backup and Unreferenced Files for Sensitive Information

reviewed all the files existing within the webroot 

- [x]	OTG-CONFIG-005	Enumerate Infrastructure and Application Admin Interfaces

n/a

- [x]	OTG-CONFIG-006	Test HTTP Methods

run nessus, nikto, nmap with nmap -vv --script=http-methods 172.16.55.139 and tested manually with netcat

- [x]	OTG-CONFIG-007	Test HTTP Strict Transport Security

have issue to add such header

- [x]	OTG-CONFIG-008	Test RIA cross domain policy

have issue to add such header

#### Identity Management Testing
- [x]	OTG-IDENT-001	Test Role Definitions

1 role only

- [x]	OTG-IDENT-002	Test User Registration Process

n/a

- [x]	OTG-IDENT-003	Test Account Provisioning Process

n/a

- [x]	OTG-IDENT-004	Testing for Account Enumeration and Guessable User Account

have issue for user enumeration

- [x]	OTG-IDENT-005	Testing for Weak or unenforced username policy

n/a

- [x]	OTG-IDENT-006	Test Permissions of Guest/Training Accounts

n/a 

- [x]	OTG-IDENT-007	Test Account Suspension/Resumption Process

n/a

#### Authentication Testing
- [ ]	OTG-AUTHN-001	Testing for Credentials Transported over an Encrypted Channel

to be fixed in the web server that we will deploy. panda shop is vuln to this.

- [x]	OTG-AUTHN-002	Testing for default credentials

everything is default we have no user provisioning

- [ ]	OTG-AUTHN-003	Testing for Weak lock out mechanism

no user lockout exists

- [ ]	OTG-AUTHN-004	Testing for bypassing authentication schema

not yet done testing

- [ ]	OTG-AUTHN-005	Test remember password functionality

have identified relevant issue

- [ ]	OTG-AUTHN-006	Testing for Browser cache weakness

have identified relevant issue (see secure headers)

- [x]	OTG-AUTHN-007	Testing for Weak password policy

n/a

- [x]	OTG-AUTHN-008	Testing for Weak security question/answer

n/a

- [x]	OTG-AUTHN-009	Testing for weak password change or reset functionalities

n/a

- [x]	OTG-AUTHN-010	Testing for Weaker authentication in alternative channel

n/a

#### Authorization Testing
- [ ]	OTG-AUTHZ-001	Testing Directory traversal/file include

TBD

- [ ]	OTG-AUTHZ-002	Testing for bypassing authorization schema

TBD

- [ ]	OTG-AUTHZ-003	Testing for Privilege Escalation

TBD

- [ ]	OTG-AUTHZ-004	Testing for Insecure Direct Object References

TBD

#### Session Management Testing
- [x]	OTG-SESS-001	Testing for Bypassing Session Management Schema
- [ ]	OTG-SESS-002	Testing for Cookies attributes

have created relevant issue

- [x]	OTG-SESS-003	Testing for Session Fixation
- [x]	OTG-SESS-004	Testing for Exposed Session Variables
- [x]	OTG-SESS-005	Testing for Cross Site Request Forgery
- [x]	OTG-SESS-006	Testing for logout functionality
- [ ]	OTG-SESS-007	Test Session Timeout

Haven't tested it yet

- [x]	OTG-SESS-008	Testing for Session puzzling


#### Data Validation Testing
- [ ]	OTG-INPVAL-001	Testing for Reflected Cross Site Scripting
- [ ]	OTG-INPVAL-002	Testing for Stored Cross Site Scripting
- [ ]	OTG-INPVAL-003	Testing for HTTP Verb Tampering
- [ ]	OTG-INPVAL-004	Testing for HTTP Parameter pollution
- [ ]	OTG-INPVAL-005	Testing for SQL Injection
						Oracle Testing
						MySQL Testing
						SQL Server Testing
						Testing PostgreSQL
						MS Access Testing
						Testing for NoSQL injection
- [ ]	OTG-INPVAL-006	Testing for LDAP Injection
- [ ]	OTG-INPVAL-007	Testing for ORM Injection
- [ ]	OTG-INPVAL-008	Testing for XML Injection
- [ ]	OTG-INPVAL-009	Testing for SSI Injection
- [ ]	OTG-INPVAL-010	Testing for XPath Injection
- [ ]	OTG-INPVAL-011	IMAP/SMTP Injection
- [ ]	OTG-INPVAL-012	Testing for Code Injection
						Testing for Local File Inclusion
						Testing for Remote File Inclusion
- [ ]	OTG-INPVAL-013	Testing for Command Injection
- [ ]	OTG-INPVAL-014	Testing for Buffer overflow
						Testing for Heap overflow
						Testing for Stack overflow
- [ ]					Testing for Format string
- [ ]	OTG-INPVAL-015	Testing for incubated vulnerabilities
- [ ]	OTG-INPVAL-016	Testing for HTTP Splitting/Smuggling
#### Error Handling
- [ ]	OTG-ERR-001		Analysis of Error Codes
- [ ]	OTG-ERR-002		Analysis of Stack Traces
#### Cryptography
- [ ]	OTG-CRYPST-001	Testing for Weak SSL/TSL Ciphers, Insufficient Transport Layer Protection
- [ ]	OTG-CRYPST-002	Testing for Padding Oracle
- [ ]	OTG-CRYPST-003	Testing for Sensitive information sent via unencrypted channels
#### Business Logic Testing
- [ ]	OTG-BUSLOGIC-001	Test Business Logic Data Validation
- [ ]	OTG-BUSLOGIC-002	Test Ability to Forge Requests
- [ ]	OTG-BUSLOGIC-003	Test Integrity Checks
- [ ]	OTG-BUSLOGIC-004	Test for Process Timing
- [ ]	OTG-BUSLOGIC-005	Test Number of Times a Function Can be Used Limits
- [ ]	OTG-BUSLOGIC-006	Testing for the Circumvention of Work Flows
- [ ]	OTG-BUSLOGIC-007	Test Defenses Against Application Mis-use
- [ ]	OTG-BUSLOGIC-008	Test Upload of Unexpected File Types
- [ ]	OTG-BUSLOGIC-009	Test Upload of Malicious Files
#### Client Side Testing
- [ ]	OTG-CLIENT-001	Testing for DOM based Cross Site Scripting
- [ ]	OTG-CLIENT-002	Testing for JavaScript Execution
- [ ]	OTG-CLIENT-003	Testing for HTML Injection
- [ ]	OTG-CLIENT-004	Testing for Client Side URL Redirect
- [ ]	OTG-CLIENT-005	Testing for CSS Injection
- [ ]	OTG-CLIENT-006	Testing for Client Side Resource Manipulation
- [ ]	OTG-CLIENT-007	Test Cross Origin Resource Sharing
- [ ]	OTG-CLIENT-008	Testing for Cross Site Flashing
- [ ]	OTG-CLIENT-009	Testing for Clickjacking
- [ ]	OTG-CLIENT-010	Testing WebSockets
- [ ]	OTG-CLIENT-011	Test Web Messaging
- [ ]	OTG-CLIENT-012	Test Local Storage
